export const FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";

export const FETCH_ALBUMS_SUCCESS = "FETCH_ARTIST_SUCCESS";

export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const ADD_TRACK_TO_HISTORY_SUCCESS = "ADD_TRACK_TO_HISTORY_SUCCESS";
export const ADD_TRACK_TO_HISTORY_FAILURE = "ADD_TRACK_TO_HISTORY_FAILURE";

export const FETCH_TRACK_HISTORY_SUCCESS = "FETCH_TRACK_HISTORY_SUCCESS";
export const FETCH_TRACK_HISTORY_FAILURE = "FETCH_TRACK_HISTORY_FAILURE";