export const FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ARTIST_SUCCESS";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";

export const FETCH_FAILURE = "FETCH_FAILURE";

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const ADD_TRACK_TO_HISTORY_SUCCESS = "ADD_TRACK_TO_HISTORY_SUCCESS";
export const ADD_TRACK_TO_HISTORY_FAILURE = "ADD_TRACK_TO_HISTORY_FAILURE";

export const FETCH_TRACK_HISTORY_SUCCESS = "FETCH_TRACK_HISTORY_SUCCESS";
export const FETCH_TRACK_HISTORY_FAILURE = "FETCH_TRACK_HISTORY_FAILURE";

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_ARTIST_SUCCESS = "CREATE_ARTIST_SUCCESS";
export const CREATE_ARTIST_FAILURE = "CREATE_ARTIST_FAILURE";

export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_ALBUM_FAILURE = "CREATE_ALBUM_FAILURE";

export const CREATE_TRACK_SUCCESS = "CREATE_TRACK_SUCCESS";
export const CREATE_TRACK_FAILURE = "CREATE_TRACK_FAILURE";


